### PR TITLE
fix: strip indent from `<<-` heredocs as defined in the HCL spec

### PR DESCRIPTION
**Pull request by martinohmann**
This was a known issue reported as part of #9.

Also adds the heredoc test case from the original HCL specsuite.

### CODE REVIEW

**Comment by martinohmann** [comment]
@venix1 since you discovered this spec violation I'd be happy to hear your thoughts on the fix.

**Comment by venix1** [comment]
@martinohmann  :+1: :+1:  Your changes nail the issue.

**Comment by martinohmann** [comment]
@venix1 actually I messed up here. The implementation was ok, but I added the wrong expectations for the added tests. See #13 (fixes test expectations and adjusts parser) and #15 (fixes tab/unicode indent issue marked as ignore in #13).

**Comment by venix1** [comment]
Thanks for fixing it so fast.  I had noticed this morning but you had the fixes already committed before I could open my text editor.

What I did noticed is that the failure output required some additional formatting to make it immediately useful.  I opened #17 to address that.

**Pull request merged**
