### PR TITLE
fix(structure): handle absence of trailing newline in body

### LINKED ISSUE #270: hcl-edit: hardcoded newline for Body
`hcl-edit` roundtrip on `Body`:

- "`foo = \"bar\"`" => "`foo = \"bar\"\n`" (0 != 1 newline)
- "`foo = \"bar\"\n`" => "`foo = \"bar\"\n`" (1 == 1 newline)
- "`foo = \"bar\"\n\n`" => "`foo = \"bar\"\n\n`" (2 == 2 newlines)

For the first case I would expect there to be no newline in the result.

There seems to be a static newline here
https://github.com/martinohmann/hcl-rs/blob/b92d3d49920683c83bf70008c8c6f832c0cf5481/crates/hcl-edit/src/encode/structure.rs#L12 and something is eating up a newline in the parser

### PR DESCRIPTION
**Pull request by martinohmann**
Fixes #270
Closes #271

### CODE REVIEW

**Comment by martinohmann** [comment]
@denfren This is how I would fix #270, happy about feedback.

**Comment by denfren** [comment]
Looking good! My only thought is that i would change `prefer_trailing_newline` => `prefer_omit_trailing_newline` because omitting is the special case that is being requested.

**Comment by martinohmann** [comment]
> Looking good! My only thought is that i would change `prefer_trailing_newline` => `prefer_omit_trailing_newline` because omitting is the special case that is being requested.

Yeah, that's better, I was about to copy that from your draft implementation. Will update the PR.

**Comment by martinohmann** [comment]
@denfren Updated

**Review by denfren — APPROVED** [review]

**Pull request merged**
