### PR TITLE
feat(bench): Make it easier to profile benchmarks

### PR DESCRIPTION
**Pull request by epage**
These are practices I pulled over from toml_edit when working on the performance regression caused by winnow-rs/winnow#98.  Feel free to pick and choose what you want from this.

### CODE REVIEW

**Comment by martinohmann** [comment]
Thanks. I read your recent blog post about testing, but I'm still not sure how this can help with profiling. Is it because you avoid the libtest/criterion layer here?

**Comment by martinohmann** [comment]
I see, thanks for the clarification!

**Comment by martinohmann** [comment]
@epage This has been sitting here for almost a year now because I was hesitant for a while and then I simply forgot about it. It's conflicted now. If you can spare some of your valueable time to rebase it, I'd be happy to merge it. :)

**Comment by epage** [comment]
Eh, haven't had a need in this for a while

**Pull request closed without merging**
